SELECT DISTINCT ao.ANIMAL_ID, ao.ANIMAL_TYPE, ao.NAME
FROM ANIMAL_OUTS AS ao
JOIN ANIMAL_INS AS ai ON ao.ANIMAL_ID = ai.ANIMAL_ID
WHERE ai.SEX_UPON_INTAKE LIKE '%Intact%'
  AND (ao.SEX_UPON_OUTCOME LIKE '%Neutered%' 
       OR ao.SEX_UPON_OUTCOME LIKE '%Spayed%')
ORDER BY ao.ANIMAL_ID;