SELECT 
    YEAR(os.SALES_DATE) AS YEAR,
    MONTH(os.SALES_DATE) AS MONTH,
    ui.GENDER,
    COUNT(DISTINCT ui.USER_ID) AS USERS
FROM USER_INFO AS ui
JOIN ONLINE_SALE AS os ON ui.USER_ID = os.USER_ID
WHERE ui.GENDER IS NOT NULL
GROUP BY YEAR(os.SALES_DATE), MONTH(os.SALES_DATE), ui.GENDER
ORDER BY YEAR, MONTH, ui.GENDER;