WITH TMP AS (SELECT 
                H.HISTORY_ID, 
                C.DAILY_FEE, 
                DATEDIFF(H.END_DATE, H.START_DATE)+1 AS 'RENTAL_DAYS', 
                CASE WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 90 THEN '90일 이상'
                    WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 30 THEN '30일 이상'
                    WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 7 THEN '7일 이상'
                    ELSE '7일 이하' 
                END AS DURATION_TYPE 
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
            JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID = H.CAR_ID
            WHERE CAR_TYPE = '트럭')

SELECT HISTORY_ID
    , IF(P.DURATION_TYPE IS NULL, TMP.DAILY_FEE * TMP.RENTAL_DAYS, ROUND((TMP.DAILY_FEE * (100 - P.DISCOUNT_RATE) * 0.01) * TMP.RENTAL_DAYS,0)) AS 'FEE'
FROM TMP
LEFT JOIN (
    SELECT * 
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE CAR_TYPE = '트럭') AS P
ON TMP.DURATION_TYPE = P.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC