WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR + 1 
    FROM HOURS 
    WHERE HOUR < 23
)

SELECT 
    H.HOUR, 
    COUNT(AO.ANIMAL_ID) AS COUNT
FROM HOURS H
LEFT JOIN ANIMAL_OUTS AO ON H.HOUR = HOUR(AO.DATETIME)
GROUP BY H.HOUR
ORDER BY H.HOUR;

-- 다른 풀이
# SET @hour := -1; # 변수 선언문

# SELECT (@hour := @hour + 1) as HOUR,
# (	SELECT COUNT(DATETIME) 
# 	FROM ANIMAL_OUTS 
# 	WHERE HOUR(DATETIME) = @hour) as COUNT
# FROM ANIMAL_OUTS
# WHERE @hour < 23
