WITH FILTERED_FOOD AS (
    SELECT * FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
)
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FILTERED_FOOD
WHERE PRICE = (SELECT MAX(PRICE) 
               FROM FILTERED_FOOD AS F 
               WHERE F.CATEGORY = FILTERED_FOOD.CATEGORY)
ORDER BY MAX_PRICE DESC;