WITH FE AS (
SELECT SUM(CODE) AS FE
FROM SKILLCODES 
WHERE CATEGORY = 'Front End'
),

PY AS (
SELECT CODE AS PY
FROM SKILLCODES WHERE NAME = 'Python'
), 

CS AS (
SELECT CODE AS CS
FROM SKILLCODES 
WHERE NAME = 'C#'
),

GR AS(
SELECT CASE
    WHEN (SKILL_CODE & FE) AND (SKILL_CODE & PY) THEN 'A'
    WHEN SKILL_CODE & CS THEN 'B'
    WHEN SKILL_CODE & FE THEN 'C'
    END AS GRADE
    , ID
    , EMAIL
FROM DEVELOPERS, FE, PY, CS
)

SELECT * 
FROM GR
WHERE GRADE IS NOT NULL
ORDER BY GRADE ASC, ID ASC